name: Run SSH Command and Script

on:
  schedule:
    - cron: '0 */6 * * *'  # This cron expression runs the job every 6 hours.
    workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Client and sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client sshpass

      - name: Run Python script over SSH
        run: |
          sshpass -p "Chomulal123" ssh -o StrictHostKeyChecking=no prize-figure-fah@sgp.domcloud.co 'cd public_html/scan && python -u sc71-73.py'
